### PR TITLE
Updated/Future-proofed addthecrit

### PR DESCRIPTION
**Pull request by Starblaster64**
Updated addthecrit from ItemIDs to weaponclassnames where appropriate. The original Critlist is now commented out, as there is nothing that needs to be in it currently.

### CODE REVIEW

**Comment by Chdata** [comment]
I think you gave the nocrit smg cozy camper some crits

**Comment by Starblaster64** [comment]
`if ((TF2_GetPlayerClass(client) == TFClass_Pyro && flindex == 594) || (IsValidEntity(FindPlayerBack(client, { 642 }, 1)))) // No crits if using Phlogistinator or Cozy Camper` should catch Phlog and Camper right?

EDIT: I could probably even remove the Pyro class check if you wanted.

**Comment by Starblaster64** [comment]
I did test it before uploading too, and everything seemed to be working fine on my end.

**Comment by Chdata** [comment]
oh didn't see that line, looks fine

**Pull request merged**
